{{- range $secret := .Values.secret }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ $secret.name }}
  namespace: {{$secret.namespace}}
type: Opaque
stringData:
  username: {{ $secret.data.dbUsername  }}
  password: {{ $secret.data.dbPassword  }}
{{- end}}
